services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mongodb
      - redis
    command: deno task dev

  worker:
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - mongodb
      - redis
      - app
    command: deno task worker
    deploy:
      mode: replicated
      replicas: 3

  mongodb:
    image: mongo:8@sha256:2e018e386e891d2e4239aca6035fb7701dac51b72891247ecd2f95ff8a167859
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb_password
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:8.0@sha256:a4b90e7079b67c41bdf4ca6f9d87197079e4c1c3273b7f489a74f2687d85a05e
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongodb-data:
  redis-data:
