services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mongodb
      - redis
    command: deno task dev

  worker:
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - mongodb
      - redis
      - app
    command: deno task worker
    deploy:
      mode: replicated
      replicas: 3

  mongodb:
    image: mongo:8@sha256:9f67b6bafda002f7bcad9939e4d84c3b4e9b11ffff6c1f9fab3f77e30c646304
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb_password
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:8.0@sha256:b3ad79880c88e302deb5e0fed6cee3e90c0031eb90cd936b01ef2f83ff5b3ff2
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongodb-data:
  redis-data:
