services:
  unbound_exporter:
    build: .
    command: [ "-unbound.host=unix:///var/run/socket/unbound.ctl" ]
    volumes:
      - socket:/var/run/socket:ro
    ports:
      - "9167:9167"
    depends_on:
      unbound:
        condition: service_started
  unbound:
    image: ghcr.io/klutchell/unbound:v1.23.0@sha256:17ea6e14cfed57506c9db69686eb4de665056a342922727f3a6bbea50be184e4
    volumes:
      - socket:/var/run/socket:rw
      - ./test_assets/unbound.conf:/opt/unbound/etc/unbound/unbound.conf
      - ./test_assets/droplist.zone:/opt/unbound/etc/unbound/droplist.zone
    ports:
      - "1053:1053/udp"
      - "1053:1053/tcp"
volumes:
  socket: